name = "ArmaForces - RHS Stryker BFT Fix"
modname = "armaforces_rhs_stryker"
prefix = "armaforces"
author = "ArmaForces"
version = "1.0.0"
files = ["mod.cpp"]

exclude = ["*.psd", "*.png", "*.tga"]

keyname = "{{prefix}}_rhs_stryker_{{version}}"
signame = "{{prefix}}_rhs_stryker_{{version}}"
reuse_private_key = true

releasebuild = [
    "!Set_version",
    "@zip",
    "!publish"
]

[scripts]
    [scripts.Set_version]
        steps_windows = [
            "powershell ./tools/Set-Version.ps1 {{version}} '@armaforces_rhs_stryker'"
        ]
        # show_output = true

    [scripts.publish]
        steps_windows = [
            "powershell ./tools/Publish.ps1 {{version}} YOUR_WORKSHOP_ID '@armaforces_rhs_stryker'"
        ]
        show_output = true
